version: "3.9"

services:
  redis:
   image: redis:7-alpine
   container_name: task-queue-redis
   ports:
    - "6379:6379"
   command: redis-server --appendonly yes
   volumes:
    - redis_data:/data
   healthcheck:
    test: ["CMD", "redis-cli", "ping"]
    interval: 5s
    timeout: 5s
    retries: 5

  app:
   build: .
   container_name: task-queue-app
   ports:
   - "8080:8080"
   environment:
     REDIS_ADDR: redis:6379
     REDIS_PASS: ""
     QUEUE_NAME: task_queue
     WORKER_COUNT: "5"
     API_PORT: "8080"
   depends_on:
     - redis
   restart: on-failure

volumes:
  redis_data: